# Site settings
title: Switch Online MD S.A.
email: marketing1@corporaciongrubal.com
description: Bienvenido a la pagina web de Switch Online MD S.A., una empresa especializada en...
baseurl: "/web/" # the subpath of your site, e.g. /blog/
url: "https://switch-on-line-md.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: dominique120

# Build settings
markdown: kramdown

google_site_verification: i_2XqOofjb7L5RxxP_aOa1eI352Xj8x6Jbo9hvUaHjM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

